name: weather_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  http: ^0.13.5
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  
  #assets:
   # - assets/city.list.json

  
