final List<Map<String, String>> citiesList = [
  // Existing cities
  {'city': 'Delhi', 'countryCode': 'IN'},

  {'city': 'Mumbai', 'countryCode': 'IN'},
  {'city': 'Bangalore', 'countryCode': 'IN'},
  {'city': 'Hyderabad', 'countryCode': 'IN'},
  {'city': 'Ahmedabad', 'countryCode': 'IN'},
  {'city': 'Chennai', 'countryCode': 'IN'},
  {'city': 'Kolkata', 'countryCode': 'IN'},
  {'city': 'Jaipur', 'countryCode': 'IN'},
  {'city': 'Pune', 'countryCode': 'IN'},
  {'city': 'Surat', 'countryCode': 'IN'},
  {'city': 'Kanpur', 'countryCode': 'IN'},
  {'city': 'Nagpur', 'countryCode': 'IN'},
  {'city': 'Goa', 'countryCode': 'IN'},
  {'city': 'Meghālaya', 'countryCode': 'IN'},
  {'city': 'Cherrapunji', 'countryCode': 'IN'},
  {'city': 'Indore', 'countryCode': 'IN'},
  {'city': 'Thane', 'countryCode': 'IN'},
  {'city': 'Bhopal', 'countryCode': 'IN'},
  {'city': 'Visakhapatnam', 'countryCode': 'IN'},
  {'city': 'Vadodara', 'countryCode': 'IN'},
  {'city': 'Ludhiana', 'countryCode': 'IN'},
  {'city': 'Agra', 'countryCode': 'IN'},
  {'city': 'Meerut', 'countryCode': 'IN'},
  {'city': 'Varanasi', 'countryCode': 'IN'},
  {'city': 'Srinagar', 'countryCode': 'IN'},
  {'city': 'Amritsar', 'countryCode': 'IN'},
  {'city': 'Ranchi', 'countryCode': 'IN'},
  {'city': 'Jamshedpur', 'countryCode': 'IN'},
  {'city': 'Howrah', 'countryCode': 'IN'},
  {'city': 'Chandigarh', 'countryCode': 'IN'},
  {'city': 'Mysore', 'countryCode': 'IN'},
  {'city': 'Bhubaneswar', 'countryCode': 'IN'},
  {'city': 'Kochi', 'countryCode': 'IN'},
  {'city': 'Coimbatore', 'countryCode': 'IN'},
  {'city': 'Nashik', 'countryCode': 'IN'},
  {'city': 'Tiruchirappalli', 'countryCode': 'IN'},
  {'city': 'Udaipur', 'countryCode': 'IN'},
  {'city': 'Raipur', 'countryCode': 'IN'},
  {'city': 'Gwalior', 'countryCode': 'IN'},
  {'city': 'Dehradun', 'countryCode': 'IN'},
  {'city': 'Shillong', 'countryCode': 'IN'},
  {'city': 'Agartala', 'countryCode': 'IN'},
  {'city': 'Gangtok', 'countryCode': 'IN'},
  {'city': 'Imphal', 'countryCode': 'IN'},
  {'city': 'Aizawl', 'countryCode': 'IN'},
  {'city': 'Dimapur', 'countryCode': 'IN'},
  {'city': 'Itanagar', 'countryCode': 'IN'},
  {'city': 'Kurnool', 'countryCode': 'IN'},
  {'city': 'Warangal', 'countryCode': 'IN'},
  {'city': 'Rourkela', 'countryCode': 'IN'},
  {'city': 'Jodhpur', 'countryCode': 'IN'},
  {'city': 'Bikaner', 'countryCode': 'IN'},
  {'city': 'Mangalore', 'countryCode': 'IN'},
  {'city': 'Tirupati', 'countryCode': 'IN'},
  {'city': 'Sangli', 'countryCode': 'IN'},
  {'city': 'Kolhapur', 'countryCode': 'IN'},
  {'city': 'Aurangabad', 'countryCode': 'IN'},
  {'city': 'Nanded', 'countryCode': 'IN'},
  {'city': 'Jabalpur', 'countryCode': 'IN'},
  {'city': 'Sagar', 'countryCode': 'IN'},
  {'city': 'Bilaspur', 'countryCode': 'IN'},
  {'city': 'Chhindwara', 'countryCode': 'IN'},
  {'city': 'Kakinada', 'countryCode': 'IN'},
  {'city': 'Nellore', 'countryCode': 'IN'},
  {'city': 'Patna', 'countryCode': 'IN'},
  {'city': 'Bhagalpur', 'countryCode': 'IN'},
  {'city': 'Muzaffarpur', 'countryCode': 'IN'},
  {'city': 'Dhanbad', 'countryCode': 'IN'},
  {'city': 'Jhansi', 'countryCode': 'IN'},
  {'city': 'Haridwar', 'countryCode': 'IN'},
  {'city': 'Haldwani', 'countryCode': 'IN'},
  {'city': 'Moradabad', 'countryCode': 'IN'},
  {'city': 'Aligarh', 'countryCode': 'IN'},
  {'city': 'Rampur', 'countryCode': 'IN'},
  {'city': 'Bareilly', 'countryCode': 'IN'},
  {'city': 'Firozabad', 'countryCode': 'IN'},
  {'city': 'Etawah', 'countryCode': 'IN'},
  {'city': 'Kanpur Dehat', 'countryCode': 'IN'},
  {'city': 'Pilibhit', 'countryCode': 'IN'},
  {'city': 'Shivamogga', 'countryCode': 'IN'},
  {'city': 'Davangere', 'countryCode': 'IN'},
  {'city': 'Gulbarga', 'countryCode': 'IN'},
  {'city': 'Kolar', 'countryCode': 'IN'},
  {'city': 'Chittoor', 'countryCode': 'IN'},
  {'city': 'Kadapa', 'countryCode': 'IN'},
  {'city': 'Anantapur', 'countryCode': 'IN'},
  {'city': 'Karimnagar', 'countryCode': 'IN'},
  {'city': 'Medak', 'countryCode': 'IN'},
  {'city': 'Nizamabad', 'countryCode': 'IN'},
  {'city': 'Tirunelveli', 'countryCode': 'IN'},
  {'city': 'Thanjavur', 'countryCode': 'IN'},
  {'city': 'Salem', 'countryCode': 'IN'},
  {'city': 'Dindigul', 'countryCode': 'IN'},
  {'city': 'Erode', 'countryCode': 'IN'},
  {'city': 'Tiruchirapalli', 'countryCode': 'IN'},
  {'city': 'Ramanathapuram', 'countryCode': 'IN'},
  {'city': 'Cuddalore', 'countryCode': 'IN'},
  {'city': 'Nagercoil', 'countryCode': 'IN'},
  {'city': 'Arakkonam', 'countryCode': 'IN'},
  {'city': 'Vellore', 'countryCode': 'IN'},
  {'city': 'Kanchipuram', 'countryCode': 'IN'},
  {'city': 'Tiruppur', 'countryCode': 'IN'},
  {'city': 'Pondicherry', 'countryCode': 'IN'},
  {'city': 'Bokaro', 'countryCode': 'IN'},
  {'city': 'Bhubaneshwar', 'countryCode': 'IN'},
  {'city': 'Chandrapur', 'countryCode': 'IN'},
  {'city': 'Gurgaon', 'countryCode': 'IN'},
  {'city': 'Haryana', 'countryCode': 'IN'},
  {'city': 'Hazaribagh', 'countryCode': 'IN'},
  {'city': 'Jalgaon', 'countryCode': 'IN'},
  {'city': 'Jalna', 'countryCode': 'IN'},
  {'city': 'Madhubani', 'countryCode': 'IN'},
  {'city': 'Mau', 'countryCode': 'IN'},
  {'city': 'Pali', 'countryCode': 'IN'},
  {'city': 'Puducherry', 'countryCode': 'IN'},
  {'city': 'Rae Bareli', 'countryCode': 'IN'},
  {'city': 'Rudrapur', 'countryCode': 'IN'},
  {'city': 'Sambhal', 'countryCode': 'IN'},
  {'city': 'Satna', 'countryCode': 'IN'},
  {'city': 'Siliguri', 'countryCode': 'IN'},
  {'city': 'Sirmaur', 'countryCode': 'IN'},
  {'city': 'Sonebhadra', 'countryCode': 'IN'},
  {'city': 'Tuticorin', 'countryCode': 'IN'},
  {'city': 'Udhampur', 'countryCode': 'IN'},
  {'city': 'Yamunanagar', 'countryCode': 'IN'},
  // Additional unique cities
  {'city': 'Faridabad', 'countryCode': 'IN'},
  {'city': 'Jammu', 'countryCode': 'IN'},
  {'city': 'Kangra', 'countryCode': 'IN'},
  {'city': 'Patiala', 'countryCode': 'IN'},
  {'city': 'Sonepat', 'countryCode': 'IN'},
  {'city': 'Hosur', 'countryCode': 'IN'},
  {'city': 'Jalandhar', 'countryCode': 'IN'},
  {'city': 'Nagapattinam', 'countryCode': 'IN'},
  {'city': 'Kota', 'countryCode': 'IN'},
//Cities from North America
  {'city': 'New York', 'countryCode': 'US'},
  {'city': 'Los Angeles', 'countryCode': 'US'},
  {'city': 'Chicago', 'countryCode': 'US'},
  {'city': 'Houston', 'countryCode': 'US'},
  {'city': 'Phoenix', 'countryCode': 'US'},
  {'city': 'Philadelphia', 'countryCode': 'US'},
  {'city': 'San Antonio', 'countryCode': 'US'},
  {'city': 'San Diego', 'countryCode': 'US'},
  {'city': 'Dallas', 'countryCode': 'US'},
  {'city': 'San Jose', 'countryCode': 'US'},
  {'city': 'Austin', 'countryCode': 'US'},
  {'city': 'Jacksonville', 'countryCode': 'US'},
  {'city': 'San Francisco', 'countryCode': 'US'},
  {'city': 'Columbus', 'countryCode': 'US'},
  {'city': 'Indianapolis', 'countryCode': 'US'},
  {'city': 'Fort Worth', 'countryCode': 'US'},
  {'city': 'Charlotte', 'countryCode': 'US'},
  {'city': 'Seattle', 'countryCode': 'US'},
  {'city': 'Denver', 'countryCode': 'US'},
  {'city': 'Washington', 'countryCode': 'US'},
  {'city': 'Boston', 'countryCode': 'US'},
  {'city': 'El Paso', 'countryCode': 'US'},
  {'city': 'Detroit', 'countryCode': 'US'},
  {'city': 'Nashville', 'countryCode': 'US'},
  {'city': 'Memphis', 'countryCode': 'US'},
  {'city': 'Baltimore', 'countryCode': 'US'},
  {'city': 'Oklahoma City', 'countryCode': 'US'},
  {'city': 'Las Vegas', 'countryCode': 'US'},
  {'city': 'Louisville', 'countryCode': 'US'},
  {'city': 'Milwaukee', 'countryCode': 'US'},
  {'city': 'Albuquerque', 'countryCode': 'US'},
  {'city': 'Tucson', 'countryCode': 'US'},
  {'city': 'Fresno', 'countryCode': 'US'},
  {'city': 'Sacramento', 'countryCode': 'US'},
  {'city': 'Kansas City', 'countryCode': 'US'},
  {'city': 'Mesa', 'countryCode': 'US'},
  {'city': 'Atlanta', 'countryCode': 'US'},
  {'city': 'Colorado Springs', 'countryCode': 'US'},
  {'city': 'Virginia Beach', 'countryCode': 'US'},
  {'city': 'Raleigh', 'countryCode': 'US'},
  {'city': 'Omaha', 'countryCode': 'US'},
  {'city': 'Miami', 'countryCode': 'US'},
  {'city': 'Cleveland', 'countryCode': 'US'},
  {'city': 'Tulsa', 'countryCode': 'US'},
  {'city': 'Oakland', 'countryCode': 'US'},
  {'city': 'Minneapolis', 'countryCode': 'US'},
  {'city': 'Wichita', 'countryCode': 'US'},
  {'city': 'Arlington', 'countryCode': 'US'},
  {'city': 'Bakersfield', 'countryCode': 'US'},
  {'city': 'Tampa', 'countryCode': 'US'},
  {'city': 'Aurora', 'countryCode': 'US'},
  {'city': 'Honolulu', 'countryCode': 'US'},
  {'city': 'Anaheim', 'countryCode': 'US'},
  {'city': 'Santa Ana', 'countryCode': 'US'},
  {'city': 'Corpus Christi', 'countryCode': 'US'},
  {'city': 'Riverside', 'countryCode': 'US'},
  {'city': 'St. Louis', 'countryCode': 'US'},
  {'city': 'Lexington', 'countryCode': 'US'},
  {'city': 'Stockton', 'countryCode': 'US'},
  {'city': 'Cincinnati', 'countryCode': 'US'},
  {'city': 'St. Paul', 'countryCode': 'US'},
  {'city': 'Buffalo', 'countryCode': 'US'},
  {'city': 'Indianapolis', 'countryCode': 'US'},
  {'city': 'Fort Wayne', 'countryCode': 'US'},
  {'city': 'Jersey City', 'countryCode': 'US'},
  {'city': 'Chula Vista', 'countryCode': 'US'},
  {'city': 'Orlando', 'countryCode': 'US'},
  {'city': 'Cleveland', 'countryCode': 'US'},
  {'city': 'St. Petersburg', 'countryCode': 'US'},
  {'city': 'Hialeah', 'countryCode': 'US'},
  {'city': 'Henderson', 'countryCode': 'US'},
  {'city': 'Glendale', 'countryCode': 'US'},
  {'city': 'Scottsdale', 'countryCode': 'US'},
  {'city': 'Gilbert', 'countryCode': 'US'},
  {'city': 'Chandler', 'countryCode': 'US'},
  {'city': 'Fremont', 'countryCode': 'US'},
  {'city': 'Boise', 'countryCode': 'US'},
  {'city': 'Richmond', 'countryCode': 'US'},
  {'city': 'Des Moines', 'countryCode': 'US'},
  {'city': 'Modesto', 'countryCode': 'US'},
  {'city': 'Shreveport', 'countryCode': 'US'},
  {'city': 'Frisco', 'countryCode': 'US'},
  {'city': 'Baton Rouge', 'countryCode': 'US'},
  {'city': 'Tacoma', 'countryCode': 'US'},
  {'city': 'San Bernardino', 'countryCode': 'US'},
  {'city': 'Salt Lake City', 'countryCode': 'US'},
  {'city': 'Newport News', 'countryCode': 'US'},
  {'city': 'Cape Coral', 'countryCode': 'US'},
  {'city': 'Cary', 'countryCode': 'US'},
  {'city': 'Olathe', 'countryCode': 'US'},
  {'city': 'Green Bay', 'countryCode': 'US'},
  {'city': 'Waukesha', 'countryCode': 'US'},
  {'city': 'Syracuse', 'countryCode': 'US'},
  {'city': 'Madison', 'countryCode': 'US'},
  {'city': 'Huntsville', 'countryCode': 'US'},
  {'city': 'Lakeland', 'countryCode': 'US'},
  {'city': 'Odessa', 'countryCode': 'US'},
  {'city': 'Laredo', 'countryCode': 'US'},
  {'city': 'Brownsville', 'countryCode': 'US'},
  {'city': 'McAllen', 'countryCode': 'US'},
  {'city': 'Harlingen', 'countryCode': 'US'},
  {'city': 'Mission', 'countryCode': 'US'},
  {'city': 'Edinburg', 'countryCode': 'US'},
  {'city': 'Killeen', 'countryCode': 'US'},
  {'city': 'Cleburne', 'countryCode': 'US'},
  {'city': 'San Angelo', 'countryCode': 'US'},
  {'city': 'Waco', 'countryCode': 'US'},
  {'city': 'Tyler', 'countryCode': 'US'},
  {'city': 'Longview', 'countryCode': 'US'},
  {'city': 'Midland', 'countryCode': 'US'},
  {'city': 'Nacogdoches', 'countryCode': 'US'},
  {'city': 'Lufkin', 'countryCode': 'US'},
  {'city': 'Temple', 'countryCode': 'US'},
  {'city': 'Pflugerville', 'countryCode': 'US'},
  {'city': 'Harker Heights', 'countryCode': 'US'},
  {'city': 'Belton', 'countryCode': 'US'},
  {'city': 'Grapevine', 'countryCode': 'US'},
  {'city': 'Euless', 'countryCode': 'US'},
  {'city': 'Allen', 'countryCode': 'US'},
  {'city': 'Flower Mound', 'countryCode': 'US'},
  {'city': 'Colleyville', 'countryCode': 'US'},
  {'city': 'Southlake', 'countryCode': 'US'},
  {'city': 'The Colony', 'countryCode': 'US'},
  {'city': 'Carrollton', 'countryCode': 'US'},
  {'city': 'Lewisville', 'countryCode': 'US'},
  {'city': 'Irving', 'countryCode': 'US'},
  {'city': 'Grand Prairie', 'countryCode': 'US'},
  {'city': 'Garland', 'countryCode': 'US'},
  {'city': 'Mesquite', 'countryCode': 'US'},
  {'city': 'Richardson', 'countryCode': 'US'},
  {'city': 'Plano', 'countryCode': 'US'},
//Cities from South America
  {'city': 'São Paulo', 'countryCode': 'BR'},
  {'city': 'Rio de Janeiro', 'countryCode': 'BR'},
  {'city': 'Salvador', 'countryCode': 'BR'},
  {'city': 'Brasília', 'countryCode': 'BR'},
  {'city': 'Fortaleza', 'countryCode': 'BR'},
  {'city': 'Belo Horizonte', 'countryCode': 'BR'},
  {'city': 'Manaus', 'countryCode': 'BR'},
  {'city': 'Curitiba', 'countryCode': 'BR'},
  {'city': 'Recife', 'countryCode': 'BR'},
  {'city': 'Porto Alegre', 'countryCode': 'BR'},
  {'city': 'Belém', 'countryCode': 'BR'},
  {'city': 'Goiania', 'countryCode': 'BR'},
  {'city': 'São Luís', 'countryCode': 'BR'},
  {'city': 'Maceió', 'countryCode': 'BR'},
  {'city': 'Campo Grande', 'countryCode': 'BR'},
  {'city': 'João Pessoa', 'countryCode': 'BR'},
  {'city': 'Teresina', 'countryCode': 'BR'},
  {'city': 'Vitória', 'countryCode': 'BR'},
  {'city': 'Aracaju', 'countryCode': 'BR'},
  {'city': 'Uberlândia', 'countryCode': 'BR'},
  {'city': 'São Bernardo do Campo', 'countryCode': 'BR'},
  {'city': 'São José dos Campos', 'countryCode': 'BR'},
  {'city': 'Ribeirão Preto', 'countryCode': 'BR'},
  {'city': 'Juiz de Fora', 'countryCode': 'BR'},
  {'city': 'Londrina', 'countryCode': 'BR'},
  {'city': 'Maringá', 'countryCode': 'BR'},
  {'city': 'Nova Iguaçu', 'countryCode': 'BR'},
  {'city': 'Caxias do Sul', 'countryCode': 'BR'},
  {'city': 'Santos', 'countryCode': 'BR'},
  {'city': 'Ribeirão Preto', 'countryCode': 'BR'},
  {'city': 'Bauru', 'countryCode': 'BR'},
  {'city': 'Presidente Prudente', 'countryCode': 'BR'},
  {'city': 'Teresópolis', 'countryCode': 'BR'},
  {'city': 'Itaúna', 'countryCode': 'BR'},
  {'city': 'Campinas', 'countryCode': 'BR'},
  {'city': 'São Carlos', 'countryCode': 'BR'},
  {'city': 'São José do Rio Preto', 'countryCode': 'BR'},
  {'city': 'Araraquara', 'countryCode': 'BR'},
  {'city': 'Catanduva', 'countryCode': 'BR'},
  {'city': 'Taubaté', 'countryCode': 'BR'},
  {'city': 'Vila Velha', 'countryCode': 'BR'},
  {'city': 'Belo Horizonte', 'countryCode': 'BR'},
  {'city': 'São João Nepomuceno', 'countryCode': 'BR'},
  {'city': 'São Joaquim da Barra', 'countryCode': 'BR'},
  {'city': 'Juiz de Fora', 'countryCode': 'BR'},
  {'city': 'Barretos', 'countryCode': 'BR'},
  {'city': 'Colatina', 'countryCode': 'BR'},
  {'city': 'Cascavel', 'countryCode': 'BR'},
  {'city': 'Sertãozinho', 'countryCode': 'BR'},
  {'city': 'Jundiaí', 'countryCode': 'BR'},
  {'city': 'Sorocaba', 'countryCode': 'BR'},
  {'city': 'Joinville', 'countryCode': 'BR'},
  {'city': 'Blumenau', 'countryCode': 'BR'},
  {'city': 'Chapecó', 'countryCode': 'BR'},
  {'city': 'Lajeado', 'countryCode': 'BR'},
  {'city': 'Mossoró', 'countryCode': 'BR'},
  {'city': 'Natal', 'countryCode': 'BR'},
  {'city': 'São Paulo', 'countryCode': 'BR'},
  {'city': 'Buenos Aires', 'countryCode': 'AR'},
  {'city': 'Córdoba', 'countryCode': 'AR'},
  {'city': 'Rosario', 'countryCode': 'AR'},
  {'city': 'Mendoza', 'countryCode': 'AR'},
  {'city': 'La Plata', 'countryCode': 'AR'},
  {'city': 'San Miguel de Tucumán', 'countryCode': 'AR'},
  {'city': 'Salta', 'countryCode': 'AR'},
  {'city': 'San Juan', 'countryCode': 'AR'},
  {'city': 'Posadas', 'countryCode': 'AR'},
  {'city': 'Santa Fe', 'countryCode': 'AR'},
  {'city': 'Bahía Blanca', 'countryCode': 'AR'},
  {'city': 'Neuquén', 'countryCode': 'AR'},
  {'city': 'San Salvador de Jujuy', 'countryCode': 'AR'},
  {'city': 'Formosa', 'countryCode': 'AR'},
  {'city': 'San Fernando del Valle de Catamarca', 'countryCode': 'AR'},
  {'city': 'Río Cuarto', 'countryCode': 'AR'},
  {'city': 'Villa María', 'countryCode': 'AR'},
  {'city': 'San Nicolás de los Arroyos', 'countryCode': 'AR'},
  {'city': 'San Rafael', 'countryCode': 'AR'},
  {'city': 'El Calafate', 'countryCode': 'AR'},
  {'city': 'San Luis', 'countryCode': 'AR'},
  {'city': 'Resistencia', 'countryCode': 'AR'},
  {'city': 'San Fernando', 'countryCode': 'AR'},
  {'city': 'San Martín', 'countryCode': 'AR'},
  {'city': 'Villa Carlos Paz', 'countryCode': 'AR'},
  {'city': 'Luján', 'countryCode': 'AR'},
  {'city': 'La Rioja', 'countryCode': 'AR'},
  {'city': 'San Pedro', 'countryCode': 'AR'},
  {'city': 'San Javier', 'countryCode': 'AR'},
  {'city': 'Santa Rosa', 'countryCode': 'AR'},
  {'city': 'San Vicente', 'countryCode': 'AR'},
  {'city': 'Viedma', 'countryCode': 'AR'},
  {'city': 'El Palomar', 'countryCode': 'AR'},
  {'city': 'Monte Grande', 'countryCode': 'AR'},
  {'city': 'Aguadulce', 'countryCode': 'PA'},
  {'city': 'David', 'countryCode': 'PA'},
  {'city': 'Colón', 'countryCode': 'PA'},
  {'city': 'Santiago', 'countryCode': 'PA'},
  {'city': 'Las Tablas', 'countryCode': 'PA'},
  {'city': 'Penonomé', 'countryCode': 'PA'},
  {'city': 'Chitré', 'countryCode': 'PA'},
  {'city': 'La Chorrera', 'countryCode': 'PA'},
  {'city': 'Bocas del Toro', 'countryCode': 'PA'},
  {'city': 'Panama City', 'countryCode': 'PA'},
  {'city': 'Lima', 'countryCode': 'PE'},
  {'city': 'Arequipa', 'countryCode': 'PE'},
  {'city': 'Trujillo', 'countryCode': 'PE'},
  {'city': 'Callao', 'countryCode': 'PE'},
  {'city': 'Chiclayo', 'countryCode': 'PE'},
  {'city': 'Piura', 'countryCode': 'PE'},
  {'city': 'Iquitos', 'countryCode': 'PE'},
  {'city': 'Cusco', 'countryCode': 'PE'},
  {'city': 'Huancayo', 'countryCode': 'PE'},
  {'city': 'Puno', 'countryCode': 'PE'},
  {'city': 'Tacna', 'countryCode': 'PE'},
  {'city': 'Chimbote', 'countryCode': 'PE'},
  {'city': 'Ayacucho', 'countryCode': 'PE'},
  {'city': 'Juliaca', 'countryCode': 'PE'},
  {'city': 'Huaraz', 'countryCode': 'PE'},
  {'city': 'Ica', 'countryCode': 'PE'},
  {'city': 'Moyobamba', 'countryCode': 'PE'},
  {'city': 'Bagua Grande', 'countryCode': 'PE'},
  {'city': 'Sullana', 'countryCode': 'PE'},
  {'city': 'Pucallpa', 'countryCode': 'PE'},
  {'city': 'Chancay', 'countryCode': 'PE'},
  {'city': 'Chachapoyas', 'countryCode': 'PE'},
  {'city': 'Tumbes', 'countryCode': 'PE'},
  {'city': 'Huánuco', 'countryCode': 'PE'},
  {'city': 'Sicuani', 'countryCode': 'PE'},
  {'city': 'Paita', 'countryCode': 'PE'},
  {'city': 'Tarapoto', 'countryCode': 'PE'},
  {'city': 'Cajamarca', 'countryCode': 'PE'},
  {'city': 'Lambayeque', 'countryCode': 'PE'},
  {'city': 'Andahuaylas', 'countryCode': 'PE'},
  {'city': 'Huaral', 'countryCode': 'PE'},
  {'city': 'Puerto Maldonado', 'countryCode': 'PE'},
  {'city': 'Apurímac', 'countryCode': 'PE'},
  {'city': 'Lima', 'countryCode': 'PE'},
  {'city': 'La Oroya', 'countryCode': 'PE'},
  {'city': 'Ica', 'countryCode': 'PE'},
  {'city': 'Tumbes', 'countryCode': 'PE'},
  {'city': 'Pisco', 'countryCode': 'PE'},
  {'city': 'Chancay', 'countryCode': 'PE'},
  {'city': 'Talara', 'countryCode': 'PE'},
  {'city': 'Sullana', 'countryCode': 'PE'},
  {'city': 'Yurimaguas', 'countryCode': 'PE'},
  {'city': 'Jauja', 'countryCode': 'PE'},
  // African cities
  {'city': 'Lagos', 'countryCode': 'NG'},
  {'city': 'Cairo', 'countryCode': 'EG'},
  {'city': 'Kinshasa', 'countryCode': 'CD'},
  {'city': 'Johannesburg', 'countryCode': 'ZA'},
  {'city': 'Nairobi', 'countryCode': 'KE'},
  {'city': 'Abidjan', 'countryCode': 'CI'},
  {'city': 'Addis Ababa', 'countryCode': 'ET'},
  {'city': 'Algiers', 'countryCode': 'DZ'},
  {'city': 'Accra', 'countryCode': 'GH'},
  {'city': 'Dar es Salaam', 'countryCode': 'TZ'},
  {'city': 'Casablanca', 'countryCode': 'MA'},
  {'city': 'Khartoum', 'countryCode': 'SD'},
  {'city': 'Kano', 'countryCode': 'NG'},
  {'city': 'Ibadan', 'countryCode': 'NG'},
  {'city': 'Luanda', 'countryCode': 'AO'},
  {'city': 'Kampala', 'countryCode': 'UG'},
  {'city': 'Dakar', 'countryCode': 'SN'},
  {'city': 'Douala', 'countryCode': 'CM'},
  {'city': 'Bamako', 'countryCode': 'ML'},
  {'city': 'Alexandria', 'countryCode': 'EG'},
  {'city': 'Port Harcourt', 'countryCode': 'NG'},
  {'city': 'Ouagadougou', 'countryCode': 'BF'},
  {'city': 'Mogadishu', 'countryCode': 'SO'},
  {'city': 'Brazzaville', 'countryCode': 'CG'},
  {'city': 'Yaoundé', 'countryCode': 'CM'},
  {'city': 'Antananarivo', 'countryCode': 'MG'},
  {'city': 'Freetown', 'countryCode': 'SL'},
  {'city': 'Harare', 'countryCode': 'ZW'},
  {'city': 'Lusaka', 'countryCode': 'ZM'},
  {'city': 'Maputo', 'countryCode': 'MZ'},
  {'city': 'Monrovia', 'countryCode': 'LR'},
  {'city': 'Tripoli', 'countryCode': 'LY'},
  {'city': 'Nouakchott', 'countryCode': 'MR'},
  {'city': 'Windhoek', 'countryCode': 'NA'},
  {'city': 'Conakry', 'countryCode': 'GN'},
  {'city': 'Niamey', 'countryCode': 'NE'},
  {'city': 'Lomé', 'countryCode': 'TG'},
  {'city': 'Bujumbura', 'countryCode': 'BI'},
  {'city': 'Pretoria', 'countryCode': 'ZA'},
  {'city': 'Gaborone', 'countryCode': 'BW'},
  {'city': 'Blantyre', 'countryCode': 'MW'},
  {'city': 'Benghazi', 'countryCode': 'LY'},
  {'city': 'Abuja', 'countryCode': 'NG'},
  {'city': 'Asmara', 'countryCode': 'ER'},
  {'city': 'Giza', 'countryCode': 'EG'},
  {'city': 'Suez', 'countryCode': 'EG'},
  {'city': 'Bujumbura', 'countryCode': 'BI'},
  {'city': 'Kigali', 'countryCode': 'RW'},
  {'city': 'Libreville', 'countryCode': 'GA'},
  {'city': 'Bissau', 'countryCode': 'GW'},
  {'city': 'Moroni', 'countryCode': 'KM'},
  {'city': 'Juba', 'countryCode': 'SS'},
  {'city': 'Victoria', 'countryCode': 'SC'},
  {'city': 'Malabo', 'countryCode': 'GQ'},
  {'city': 'N’Djamena', 'countryCode': 'TD'},
  {'city': 'Djibouti', 'countryCode': 'DJ'},
  {'city': 'Saint-Louis', 'countryCode': 'SN'},
  {'city': 'Zanzibar City', 'countryCode': 'TZ'},
  {'city': 'Mombasa', 'countryCode': 'KE'},
  {'city': 'Port Louis', 'countryCode': 'MU'},
  {'city': 'Cape Town', 'countryCode': 'ZA'},
  {'city': 'Durban', 'countryCode': 'ZA'},
  {'city': 'Bloemfontein', 'countryCode': 'ZA'},
  {'city': 'Polokwane', 'countryCode': 'ZA'},
  {'city': 'Tunis', 'countryCode': 'TN'},
  {'city': 'Sfax', 'countryCode': 'TN'},
  {'city': 'Sousse', 'countryCode': 'TN'},
  {'city': 'Gafsa', 'countryCode': 'TN'},
  {'city': 'Tangier', 'countryCode': 'MA'},
  {'city': 'Fes', 'countryCode': 'MA'},
  {'city': 'Marrakech', 'countryCode': 'MA'},
  {'city': 'Agadir', 'countryCode': 'MA'},
  {'city': 'Rabat', 'countryCode': 'MA'},
  {'city': 'Bouaké', 'countryCode': 'CI'},
  {'city': 'Daloa', 'countryCode': 'CI'},
  {'city': 'San-Pédro', 'countryCode': 'CI'},
  {'city': 'Yamoussoukro', 'countryCode': 'CI'},
  {'city': 'Korhogo', 'countryCode': 'CI'},
  {'city': 'Lubumbashi', 'countryCode': 'CD'},
  {'city': 'Mbuji-Mayi', 'countryCode': 'CD'},
  {'city': 'Kananga', 'countryCode': 'CD'},
  {'city': 'Bukavu', 'countryCode': 'CD'},
  {'city': 'Kisangani', 'countryCode': 'CD'},
  {'city': 'Beni', 'countryCode': 'CD'},
  {'city': 'Goma', 'countryCode': 'CD'},
  {'city': 'Matadi', 'countryCode': 'CD'},
  {'city': 'Maseru', 'countryCode': 'LS'},
  {'city': 'Freetown', 'countryCode': 'SL'},
  {'city': 'Bo', 'countryCode': 'SL'},
  {'city': 'Kenema', 'countryCode': 'SL'},
  {'city': 'Makeni', 'countryCode': 'SL'},
  {'city': 'Boma', 'countryCode': 'CD'},
  {'city': 'Brazzaville', 'countryCode': 'CG'},
  {'city': 'Pointe-Noire', 'countryCode': 'CG'},
  {'city': 'Ziguinchor', 'countryCode': 'SN'},
  {'city': 'Kaolack', 'countryCode': 'SN'},
  {'city': 'Tambacounda', 'countryCode': 'SN'},
  {'city': 'Thies', 'countryCode': 'SN'},
  {'city': 'Diourbel', 'countryCode': 'SN'},
  {'city': 'Saint-Louis', 'countryCode': 'SN'},

  // Australian and Oceania cities
  {'city': 'Sydney', 'countryCode': 'AU'},
  {'city': 'Melbourne', 'countryCode': 'AU'},
  {'city': 'Brisbane', 'countryCode': 'AU'},
  {'city': 'Perth', 'countryCode': 'AU'},
  {'city': 'Adelaide', 'countryCode': 'AU'},
  {'city': 'Gold Coast', 'countryCode': 'AU'},
  {'city': 'Canberra', 'countryCode': 'AU'},
  {'city': 'Newcastle', 'countryCode': 'AU'},
  {'city': 'Wollongong', 'countryCode': 'AU'},
  {'city': 'Geelong', 'countryCode': 'AU'},
  {'city': 'Hobart', 'countryCode': 'AU'},
  {'city': 'Townsville', 'countryCode': 'AU'},
  {'city': 'Cairns', 'countryCode': 'AU'},
  {'city': 'Darwin', 'countryCode': 'AU'},
  {'city': 'Toowoomba', 'countryCode': 'AU'},
  {'city': 'Ballarat', 'countryCode': 'AU'},
  {'city': 'Bendigo', 'countryCode': 'AU'},
  {'city': 'Launceston', 'countryCode': 'AU'},
  {'city': 'Mackay', 'countryCode': 'AU'},
  {'city': 'Rockhampton', 'countryCode': 'AU'},
  {'city': 'Bundaberg', 'countryCode': 'AU'},
  {'city': 'Bunbury', 'countryCode': 'AU'},
  {'city': 'Coffs Harbour', 'countryCode': 'AU'},
  {'city': 'Shepparton', 'countryCode': 'AU'},
  {'city': 'Wagga Wagga', 'countryCode': 'AU'},
  {'city': 'Hervey Bay', 'countryCode': 'AU'},
  {'city': 'Albury', 'countryCode': 'AU'},
  {'city': 'Port Macquarie', 'countryCode': 'AU'},
  {'city': 'Orange', 'countryCode': 'AU'},
  {'city': 'Dubbo', 'countryCode': 'AU'},
  {'city': 'Kalgoorlie', 'countryCode': 'AU'},
  {'city': 'Geraldton', 'countryCode': 'AU'},
  {'city': 'Alice Springs', 'countryCode': 'AU'},
  {'city': 'Mount Gambier', 'countryCode': 'AU'},
  {'city': 'Busselton', 'countryCode': 'AU'},
  {'city': 'Mildura', 'countryCode': 'AU'},
  {'city': 'Tamworth', 'countryCode': 'AU'},
  {'city': 'Bathurst', 'countryCode': 'AU'},
  {'city': 'Gladstone', 'countryCode': 'AU'},
  {'city': 'Warrnambool', 'countryCode': 'AU'},
  {'city': 'Broome', 'countryCode': 'AU'},
  {'city': 'Victor Harbor', 'countryCode': 'AU'},
  {'city': 'Armidale', 'countryCode': 'AU'},
  {'city': 'Devonport', 'countryCode': 'AU'},
  {'city': 'Broken Hill', 'countryCode': 'AU'},
  {'city': 'Burnie', 'countryCode': 'AU'},
  {'city': 'Goulburn', 'countryCode': 'AU'},
  {'city': 'Gympie', 'countryCode': 'AU'},
  {'city': 'Mount Isa', 'countryCode': 'AU'},
  {'city': 'Parkes', 'countryCode': 'AU'},
  {'city': 'Emerald', 'countryCode': 'AU'},
  {'city': 'Mudgee', 'countryCode': 'AU'},
  {'city': 'Katherine', 'countryCode': 'AU'},
  {'city': 'Port Hedland', 'countryCode': 'AU'},
  {'city': 'Tennant Creek', 'countryCode': 'AU'},
  {'city': 'Esperance', 'countryCode': 'AU'},
  {'city': 'Manly', 'countryCode': 'AU'},
  {'city': 'Grafton', 'countryCode': 'AU'},
  {'city': 'Moruya', 'countryCode': 'AU'},
  {'city': 'Narrabri', 'countryCode': 'AU'},
  {'city': 'Wodonga', 'countryCode': 'AU'},
  {'city': 'Charters Towers', 'countryCode': 'AU'},
  {'city': 'Dalby', 'countryCode': 'AU'},
  {'city': 'Innisfail', 'countryCode': 'AU'},
  {'city': 'Kingaroy', 'countryCode': 'AU'},
  {'city': 'Goondiwindi', 'countryCode': 'AU'},
  {'city': 'Taree', 'countryCode': 'AU'},
  {'city': 'Forster', 'countryCode': 'AU'},
  {'city': 'Moss Vale', 'countryCode': 'AU'},
  {'city': 'Lithgow', 'countryCode': 'AU'},
  {'city': 'Lismore', 'countryCode': 'AU'},
  {'city': 'Ulladulla', 'countryCode': 'AU'},
  {'city': 'Yass', 'countryCode': 'AU'},
  {'city': 'Kempsey', 'countryCode': 'AU'},
  {'city': 'Winton', 'countryCode': 'AU'},
  {'city': 'Kingston', 'countryCode': 'AU'},
  {'city': 'Victor Harbor', 'countryCode': 'AU'},
  {'city': 'Port Augusta', 'countryCode': 'AU'},
  {'city': 'Whyalla', 'countryCode': 'AU'},
  {'city': 'Port Lincoln', 'countryCode': 'AU'},
  {'city': 'Ceduna', 'countryCode': 'AU'},
  {'city': 'Karratha', 'countryCode': 'AU'},
  {'city': 'Newman', 'countryCode': 'AU'},
  {'city': 'Exmouth', 'countryCode': 'AU'},
  {'city': 'Narrogin', 'countryCode': 'AU'},
  {'city': 'Yulara', 'countryCode': 'AU'},
  {'city': 'Auckland', 'countryCode': 'NZ'},
  {'city': 'Wellington', 'countryCode': 'NZ'},
  {'city': 'Christchurch', 'countryCode': 'NZ'},
  {'city': 'Hamilton', 'countryCode': 'NZ'},
  {'city': 'Dunedin', 'countryCode': 'NZ'},
  {'city': 'Rotorua', 'countryCode': 'NZ'},
  {'city': 'Queenstown', 'countryCode': 'NZ'},
  {'city': 'Napier', 'countryCode': 'NZ'},
  {'city': 'Nelson', 'countryCode': 'NZ'},
  {'city': 'Taupo', 'countryCode': 'NZ'},
  {'city': 'Blenheim', 'countryCode': 'NZ'},
  {'city': 'Invercargill', 'countryCode': 'NZ'},
  {'city': 'Palmerston North', 'countryCode': 'NZ'},
  {'city': 'New Plymouth', 'countryCode': 'NZ'},
  {'city': 'Hastings', 'countryCode': 'NZ'},
  {'city': 'Tauranga', 'countryCode': 'NZ'},

  {'city': 'London', 'countryCode': 'GB'},
  {'city': 'Paris', 'countryCode': 'FR'},
  {'city': 'Berlin', 'countryCode': 'DE'},
  {'city': 'Madrid', 'countryCode': 'ES'},
  {'city': 'Rome', 'countryCode': 'IT'},
  {'city': 'Amsterdam', 'countryCode': 'NL'},
  {'city': 'Vienna', 'countryCode': 'AT'},
  {'city': 'Brussels', 'countryCode': 'BE'},
  {'city': 'Stockholm', 'countryCode': 'SE'},
  {'city': 'Copenhagen', 'countryCode': 'DK'},
  {'city': 'Dublin', 'countryCode': 'IE'},
  {'city': 'Lisbon', 'countryCode': 'PT'},
  {'city': 'Zurich', 'countryCode': 'CH'},
  {'city': 'Oslo', 'countryCode': 'NO'},
  {'city': 'Helsinki', 'countryCode': 'FI'},
  {'city': 'Warsaw', 'countryCode': 'PL'},
  {'city': 'Prague', 'countryCode': 'CZ'},
  {'city': 'Budapest', 'countryCode': 'HU'},
  {'city': 'Athens', 'countryCode': 'GR'},
  {'city': 'Sofia', 'countryCode': 'BG'},
  {'city': 'Belgrade', 'countryCode': 'RS'},
  {'city': 'Bucharest', 'countryCode': 'RO'},
  {'city': 'Kiev', 'countryCode': 'UA'},
  {'city': 'Minsk', 'countryCode': 'BY'},
  {'city': 'Riga', 'countryCode': 'LV'},
  {'city': 'Vilnius', 'countryCode': 'LT'},
  {'city': 'Tallinn', 'countryCode': 'EE'},
  {'city': 'Zagreb', 'countryCode': 'HR'},
  {'city': 'Sarajevo', 'countryCode': 'BA'},
  {'city': 'Ljubljana', 'countryCode': 'SI'},
  {'city': 'Skopje', 'countryCode': 'MK'},
  {'city': 'Podgorica', 'countryCode': 'ME'},
  {'city': 'Tirana', 'countryCode': 'AL'},
  {'city': 'Luxembourg', 'countryCode': 'LU'},
  {'city': 'Reykjavik', 'countryCode': 'IS'},
  {'city': 'Valletta', 'countryCode': 'MT'},
  {'city': 'Andorra la Vella', 'countryCode': 'AD'},
  {'city': 'Monaco', 'countryCode': 'MC'},
  {'city': 'San Marino', 'countryCode': 'SM'},
  {'city': 'Vatican City', 'countryCode': 'VA'},
  {'city': 'Porto', 'countryCode': 'PT'},
  {'city': 'Seville', 'countryCode': 'ES'},
  {'city': 'Barcelona', 'countryCode': 'ES'},
  {'city': 'Lyon', 'countryCode': 'FR'},
  {'city': 'Nice', 'countryCode': 'FR'},
  {'city': 'Marseille', 'countryCode': 'FR'},
  {'city': 'Munich', 'countryCode': 'DE'},
  {'city': 'Frankfurt', 'countryCode': 'DE'},
  {'city': 'Hamburg', 'countryCode': 'DE'},
  {'city': 'Cologne', 'countryCode': 'DE'},
  {'city': 'Stuttgart', 'countryCode': 'DE'},
  {'city': 'Dusseldorf', 'countryCode': 'DE'},
  {'city': 'Birmingham', 'countryCode': 'GB'},
  {'city': 'Manchester', 'countryCode': 'GB'},
  {'city': 'Edinburgh', 'countryCode': 'GB'},
  {'city': 'Glasgow', 'countryCode': 'GB'},
  {'city': 'Liverpool', 'countryCode': 'GB'},
  {'city': 'Leeds', 'countryCode': 'GB'},
  {'city': 'Sheffield', 'countryCode': 'GB'},
  {'city': 'Bristol', 'countryCode': 'GB'},
  {'city': 'Dortmund', 'countryCode': 'DE'},
  {'city': 'Rotterdam', 'countryCode': 'NL'},
  {'city': 'The Hague', 'countryCode': 'NL'},
  {'city': 'Utrecht', 'countryCode': 'NL'},
  {'city': 'Antwerp', 'countryCode': 'BE'},
  {'city': 'Ghent', 'countryCode': 'BE'},
  {'city': 'Bruges', 'countryCode': 'BE'},
  {'city': 'Gothenburg', 'countryCode': 'SE'},
  {'city': 'Malmo', 'countryCode': 'SE'},
  {'city': 'Turku', 'countryCode': 'FI'},
  {'city': 'Odessa', 'countryCode': 'UA'},
  {'city': 'Lviv', 'countryCode': 'UA'},
  {'city': 'Krakow', 'countryCode': 'PL'},
  {'city': 'Gdansk', 'countryCode': 'PL'},
  {'city': 'Wroclaw', 'countryCode': 'PL'},
  {'city': 'Katowice', 'countryCode': 'PL'},
  {'city': 'Bratislava', 'countryCode': 'SK'},
  {'city': 'Kosice', 'countryCode': 'SK'},
  {'city': 'Plovdiv', 'countryCode': 'BG'},
  {'city': 'Varna', 'countryCode': 'BG'},
  {'city': 'Split', 'countryCode': 'HR'},
  {'city': 'Dubrovnik', 'countryCode': 'HR'},
  {'city': 'Novi Sad', 'countryCode': 'RS'},
  {'city': 'Thessaloniki', 'countryCode': 'GR'},
  {'city': 'Patras', 'countryCode': 'GR'},
  {'city': 'Ioannina', 'countryCode': 'GR'},
  {'city': 'Cork', 'countryCode': 'IE'},
  {'city': 'Limerick', 'countryCode': 'IE'},
  {'city': 'Galway', 'countryCode': 'IE'},
  {'city': 'Stavanger', 'countryCode': 'NO'},
  {'city': 'Bergen', 'countryCode': 'NO'},
  {'city': 'Trondheim', 'countryCode': 'NO'},
  {'city': 'Espoo', 'countryCode': 'FI'},
  {'city': 'Lausanne', 'countryCode': 'CH'},
  {'city': 'Basel', 'countryCode': 'CH'},
  {'city': 'Geneva', 'countryCode': 'CH'},
  {'city': 'Lucerne', 'countryCode': 'CH'},

  // Asian cities (excluding India)
  {'city': 'Tokyo', 'countryCode': 'JP'},
  {'city': 'Beijing', 'countryCode': 'CN'},
  {'city': 'Seoul', 'countryCode': 'KR'},
  {'city': 'Bangkok', 'countryCode': 'TH'},
  {'city': 'Jakarta', 'countryCode': 'ID'},
  {'city': 'Shanghai', 'countryCode': 'CN'},
  {'city': 'Hong Kong', 'countryCode': 'HK'},
  {'city': 'Kuala Lumpur', 'countryCode': 'MY'},
  {'city': 'Manila', 'countryCode': 'PH'},
  {'city': 'Singapore', 'countryCode': 'SG'},
  {'city': 'Taipei', 'countryCode': 'TW'},
  {'city': 'Ho Chi Minh City', 'countryCode': 'VN'},
  {'city': 'Hanoi', 'countryCode': 'VN'},
  {'city': 'Yangon', 'countryCode': 'MM'},
  {'city': 'Phnom Penh', 'countryCode': 'KH'},
  {'city': 'Vientiane', 'countryCode': 'LA'},
  {'city': 'Colombo', 'countryCode': 'LK'},
  {'city': 'Male', 'countryCode': 'MV'},
  {'city': 'Kathmandu', 'countryCode': 'NP'},
  {'city': 'Islamabad', 'countryCode': 'PK'},
  {'city': 'Karachi', 'countryCode': 'PK'},
  {'city': 'Lahore', 'countryCode': 'PK'},
  {'city': 'Peshawar', 'countryCode': 'PK'},
  {'city': 'Dhaka', 'countryCode': 'BD'},
  {'city': 'Chittagong', 'countryCode': 'BD'},
  {'city': 'Cox\'s Bazar', 'countryCode': 'BD'},
  {'city': 'Rangoon', 'countryCode': 'MM'},
  {'city': 'Mandalay', 'countryCode': 'MM'},
  {'city': 'Pyongyang', 'countryCode': 'KP'},
  {'city': 'Dushanbe', 'countryCode': 'TJ'},
  {'city': 'Tashkent', 'countryCode': 'UZ'},
  {'city': 'Ashgabat', 'countryCode': 'TM'},
  {'city': 'Bishkek', 'countryCode': 'KG'},
  {'city': 'Almaty', 'countryCode': 'KZ'},
  {'city': 'Astana', 'countryCode': 'KZ'},
  {'city': 'Yerevan', 'countryCode': 'AM'},
  {'city': 'Baku', 'countryCode': 'AZ'},
  {'city': 'Tbilisi', 'countryCode': 'GE'},
  {'city': 'Tehran', 'countryCode': 'IR'},
  {'city': 'Mashhad', 'countryCode': 'IR'},
  {'city': 'Isfahan', 'countryCode': 'IR'},
  {'city': 'Shiraz', 'countryCode': 'IR'},
  {'city': 'Baghdad', 'countryCode': 'IQ'},
  {'city': 'Basra', 'countryCode': 'IQ'},
  {'city': 'Mosul', 'countryCode': 'IQ'},
  {'city': 'Amman', 'countryCode': 'JO'},
  {'city': 'Aqaba', 'countryCode': 'JO'},
  {'city': 'Beirut', 'countryCode': 'LB'},
  {'city': 'Damascus', 'countryCode': 'SY'},
  {'city': 'Aleppo', 'countryCode': 'SY'},
  {'city': 'Riyadh', 'countryCode': 'SA'},
  {'city': 'Jeddah', 'countryCode': 'SA'},
  {'city': 'Mecca', 'countryCode': 'SA'},
  {'city': 'Medina', 'countryCode': 'SA'},
  {'city': 'Doha', 'countryCode': 'QA'},
  {'city': 'Abu Dhabi', 'countryCode': 'AE'},
  {'city': 'Dubai', 'countryCode': 'AE'},
  {'city': 'Muscat', 'countryCode': 'OM'},
  {'city': 'Kuwait City', 'countryCode': 'KW'},
  {'city': 'Manama', 'countryCode': 'BH'},
  {'city': 'Sana\'a', 'countryCode': 'YE'},
  {'city': 'Jerusalem', 'countryCode': 'IL'},
  {'city': 'Tel Aviv', 'countryCode': 'IL'},
  {'city': 'Haifa', 'countryCode': 'IL'},
  {'city': 'Ankara', 'countryCode': 'TR'},
  {'city': 'Istanbul', 'countryCode': 'TR'},
  {'city': 'Izmir', 'countryCode': 'TR'},
  {'city': 'Antalya', 'countryCode': 'TR'},
  {'city': 'Bursa', 'countryCode': 'TR'},
  {'city': 'Gaziantep', 'countryCode': 'TR'},
  {'city': 'Ulaanbaatar', 'countryCode': 'MN'},
  {'city': 'Sapporo', 'countryCode': 'JP'},
  {'city': 'Osaka', 'countryCode': 'JP'},
  {'city': 'Nagoya', 'countryCode': 'JP'},
  {'city': 'Fukuoka', 'countryCode': 'JP'},
  {'city': 'Kyoto', 'countryCode': 'JP'},
  {'city': 'Yokohama', 'countryCode': 'JP'},
  {'city': 'Kobe', 'countryCode': 'JP'},
  {'city': 'Sendai', 'countryCode': 'JP'},
  {'city': 'Naha', 'countryCode': 'JP'},
  {'city': 'Chongqing', 'countryCode': 'CN'},
  {'city': 'Shenzhen', 'countryCode': 'CN'},
  {'city': 'Guangzhou', 'countryCode': 'CN'},
  {'city': 'Chengdu', 'countryCode': 'CN'},
  {'city': 'Xi\'an', 'countryCode': 'CN'},
  {'city': 'Wuhan', 'countryCode': 'CN'},
  {'city': 'Suzhou', 'countryCode': 'CN'},
  {'city': 'Tianjin', 'countryCode': 'CN'},
  {'city': 'Harbin', 'countryCode': 'CN'},
  {'city': 'Hangzhou', 'countryCode': 'CN'},
  {'city': 'Macau', 'countryCode': 'MO'},
  {'city': 'Urumqi', 'countryCode': 'CN'},
  {'city': 'Lhasa', 'countryCode': 'CN'},
  {'city': 'Busan', 'countryCode': 'KR'},
  {'city': 'Incheon', 'countryCode': 'KR'},
  {'city': 'Daegu', 'countryCode': 'KR'},
  {'city': 'Daejeon', 'countryCode': 'KR'},
  {'city': 'Gwangju', 'countryCode': 'KR'},
  {'city': 'Jeju City', 'countryCode': 'KR'},

//The previously Added Countries
  {'city': 'New York', 'countryCode': 'US'},
  {'city': 'Los Angeles', 'countryCode': 'US'},
  {'city': 'Chicago', 'countryCode': 'US'},
  {'city': 'Houston', 'countryCode': 'US'},
  {'city': 'Phoenix', 'countryCode': 'US'},
  {'city': 'Philadelphia', 'countryCode': 'US'},
  {'city': 'San Antonio', 'countryCode': 'US'},
  {'city': 'San Diego', 'countryCode': 'US'},
  {'city': 'Dallas', 'countryCode': 'US'},
  {'city': 'San Jose', 'countryCode': 'US'},
  {'city': 'London', 'countryCode': 'GB'},
  {'city': 'Manchester', 'countryCode': 'GB'},
  {'city': 'Birmingham', 'countryCode': 'GB'},
  {'city': 'Glasgow', 'countryCode': 'GB'},
  {'city': 'Edinburgh', 'countryCode': 'GB'},
  {'city': 'Toronto', 'countryCode': 'CA'},
  {'city': 'Vancouver', 'countryCode': 'CA'},
  {'city': 'Montreal', 'countryCode': 'CA'},
  {'city': 'Calgary', 'countryCode': 'CA'},
  {'city': 'Ottawa', 'countryCode': 'CA'},
  {'city': 'Sydney', 'countryCode': 'AU'},
  {'city': 'Melbourne', 'countryCode': 'AU'},
  {'city': 'Brisbane', 'countryCode': 'AU'},
  {'city': 'Perth', 'countryCode': 'AU'},
  {'city': 'Adelaide', 'countryCode': 'AU'},
  {'city': 'Paris', 'countryCode': 'FR'},
  {'city': 'Marseille', 'countryCode': 'FR'},
  {'city': 'Lyon', 'countryCode': 'FR'},
  {'city': 'Toulouse', 'countryCode': 'FR'},
  {'city': 'Nice', 'countryCode': 'FR'},
  {'city': 'Berlin', 'countryCode': 'DE'},
  {'city': 'Hamburg', 'countryCode': 'DE'},
  {'city': 'Munich', 'countryCode': 'DE'},
  {'city': 'Cologne', 'countryCode': 'DE'},
  {'city': 'Frankfurt', 'countryCode': 'DE'},
  {'city': 'Rome', 'countryCode': 'IT'},
  {'city': 'Milan', 'countryCode': 'IT'},
  {'city': 'Naples', 'countryCode': 'IT'},
  {'city': 'Turin', 'countryCode': 'IT'},
  {'city': 'Florence', 'countryCode': 'IT'},
  {'city': 'Madrid', 'countryCode': 'ES'},
  {'city': 'Barcelona', 'countryCode': 'ES'},
  {'city': 'Valencia', 'countryCode': 'ES'},
  {'city': 'Seville', 'countryCode': 'ES'},
  {'city': 'Bilbao', 'countryCode': 'ES'},
  {'city': 'Amsterdam', 'countryCode': 'NL'},
  {'city': 'Rotterdam', 'countryCode': 'NL'},
  {'city': 'The Hague', 'countryCode': 'NL'},
  {'city': 'Utrecht', 'countryCode': 'NL'},
  {'city': 'Eindhoven', 'countryCode': 'NL'},
  {'city': 'Tokyo', 'countryCode': 'JP'},
  {'city': 'Osaka', 'countryCode': 'JP'},
  {'city': 'Kyoto', 'countryCode': 'JP'},
  {'city': 'Nagoya', 'countryCode': 'JP'},
  {'city': 'Hiroshima', 'countryCode': 'JP'},
  {'city': 'Beijing', 'countryCode': 'CN'},
  {'city': 'Shanghai', 'countryCode': 'CN'},
  {'city': 'Guangzhou', 'countryCode': 'CN'},
  {'city': 'Shenzhen', 'countryCode': 'CN'},
  {'city': 'Chengdu', 'countryCode': 'CN'},
  {'city': 'Singapore', 'countryCode': 'SG'},
  {'city': 'Jakarta', 'countryCode': 'ID'},
  {'city': 'Kuala Lumpur', 'countryCode': 'MY'},
  {'city': 'Manila', 'countryCode': 'PH'},
  {'city': 'Seoul', 'countryCode': 'KR'},
  {'city': 'Busan', 'countryCode': 'KR'},
  {'city': 'Dubai', 'countryCode': 'AE'},
  {'city': 'Abu Dhabi', 'countryCode': 'AE'},
  {'city': 'Tel Aviv', 'countryCode': 'IL'},
  {'city': 'Jerusalem', 'countryCode': 'IL'},
  {'city': 'Istanbul', 'countryCode': 'TR'},
  {'city': 'Ankara', 'countryCode': 'TR'},
  {'city': 'Athens', 'countryCode': 'GR'},
  {'city': 'Thessaloniki', 'countryCode': 'GR'},
  {'city': 'Vienna', 'countryCode': 'AT'},
  {'city': 'Graz', 'countryCode': 'AT'},
  {'city': 'Zurich', 'countryCode': 'CH'},
  {'city': 'Geneva', 'countryCode': 'CH'},
  {'city': 'Bern', 'countryCode': 'CH'},
  {'city': 'Stockholm', 'countryCode': 'SE'},
  {'city': 'Gothenburg', 'countryCode': 'SE'},
  {'city': 'Copenhagen', 'countryCode': 'DK'},
  {'city': 'Helsinki', 'countryCode': 'FI'},
  {'city': 'Oslo', 'countryCode': 'NO'},
  {'city': 'Reykjavik', 'countryCode': 'IS'},
  {'city': 'Dublin', 'countryCode': 'IE'},
  {'city': 'Belfast', 'countryCode': 'GB'},
  {'city': 'Edinburgh', 'countryCode': 'GB'},
  {'city': 'Glasgow', 'countryCode': 'GB'},
  {'city': 'Cardiff', 'countryCode': 'GB'},
  {'city': 'Wellington', 'countryCode': 'NZ'},
  {'city': 'Auckland', 'countryCode': 'NZ'},
  {'city': 'Christchurch', 'countryCode': 'NZ'},
  {'city': 'Brisbane', 'countryCode': 'AU'},
  {'city': 'Melbourne', 'countryCode': 'AU'},
  {'city': 'Sydney', 'countryCode': 'AU'},
  {'city': 'Perth', 'countryCode': 'AU'},
  {'city': 'Adelaide', 'countryCode': 'AU'},
  {'city': 'Lima', 'countryCode': 'PE'},
  {'city': 'Buenos Aires', 'countryCode': 'AR'},
  {'city': 'Santiago', 'countryCode': 'CL'},
  {'city': 'Rio de Janeiro', 'countryCode': 'BR'},
  {'city': 'São Paulo', 'countryCode': 'BR'},
  {'city': 'Bogotá', 'countryCode': 'CO'},
  {'city': 'Caracas', 'countryCode': 'VE'},
  {'city': 'Quito', 'countryCode': 'EC'},
  {'city': 'Asunción', 'countryCode': 'PY'},
  {'city': 'Montevideo', 'countryCode': 'UY'},
  {'city': 'La Paz', 'countryCode': 'BO'},
  {'city': 'Kiev', 'countryCode': 'UA'},
  {'city': 'Minsk', 'countryCode': 'BY'},
  {'city': 'Warsaw', 'countryCode': 'PL'},
  {'city': 'Budapest', 'countryCode': 'HU'},
  {'city': 'Prague', 'countryCode': 'CZ'},
  {'city': 'Bratislava', 'countryCode': 'SK'},
  {'city': 'Ljubljana', 'countryCode': 'SI'},
  {'city': 'Riga', 'countryCode': 'LV'},
  {'city': 'Vilnius', 'countryCode': 'LT'},
  {'city': 'Tallinn', 'countryCode': 'EE'},
  {'city': 'Sarajevo', 'countryCode': 'BA'},
  {'city': 'Belgrade', 'countryCode': 'RS'},
  {'city': 'Zagreb', 'countryCode': 'HR'},
  {'city': 'Sofia', 'countryCode': 'BG'},
  {'city': 'Bucharest', 'countryCode': 'RO'},
  {'city': 'Chisinau', 'countryCode': 'MD'},
  {'city': 'Tbilisi', 'countryCode': 'GE'},
  {'city': 'Yerevan', 'countryCode': 'AM'},
  {'city': 'Baku', 'countryCode': 'AZ'},
  {'city': 'Astana', 'countryCode': 'KZ'},
  {'city': 'Almaty', 'countryCode': 'KZ'},
  {'city': 'Ulaanbaatar', 'countryCode': 'MN'},
  {'city': 'Dhaka', 'countryCode': 'BD'},
  {'city': 'Colombo', 'countryCode': 'LK'},
  {'city': 'Kathmandu', 'countryCode': 'NP'},
  {'city': 'Thimphu', 'countryCode': 'BT'},
  {'city': 'Male', 'countryCode': 'MV'},
  {'city': 'Vientiane', 'countryCode': 'LA'},
  {'city': 'Hanoi', 'countryCode': 'VN'},
  {'city': 'Ho Chi Minh City', 'countryCode': 'VN'},
  {'city': 'Yangon', 'countryCode': 'MM'},
  {'city': 'Phnom Penh', 'countryCode': 'KH'},
  {'city': 'Kuala Lumpur', 'countryCode': 'MY'},
  {'city': 'Singapore', 'countryCode': 'SG'},
  {'city': 'Manila', 'countryCode': 'PH'},
  {'city': 'Hong Kong', 'countryCode': 'HK'},
  {'city': 'Taipei', 'countryCode': 'TW'},
  {'city': 'Seoul', 'countryCode': 'KR'},
  {'city': 'Busan', 'countryCode': 'KR'},
  {'city': 'Dubai', 'countryCode': 'AE'},
  {'city': 'Abu Dhabi', 'countryCode': 'AE'},
  {'city': 'Doha', 'countryCode': 'QA'},
  {'city': 'Kuwait City', 'countryCode': 'KW'},
  {'city': 'Manama', 'countryCode': 'BH'},
  {'city': 'Riyadh', 'countryCode': 'SA'},
  {'city': 'Jeddah', 'countryCode': 'SA'},
  {'city': 'Cairo', 'countryCode': 'EG'},
  {'city': 'Alexandria', 'countryCode': 'EG'},
  {'city': 'Casablanca', 'countryCode': 'MA'},
  {'city': 'Rabat', 'countryCode': 'MA'},
  {'city': 'Tunis', 'countryCode': 'TN'},
  {'city': 'Algiers', 'countryCode': 'DZ'},
  {'city': 'Istanbul', 'countryCode': 'TR'},
  {'city': 'Ankara', 'countryCode': 'TR'},
  {'city': 'Athens', 'countryCode': 'GR'},
  {'city': 'Thessaloniki', 'countryCode': 'GR'},
  {'city': 'Vienna', 'countryCode': 'AT'},
  {'city': 'Graz', 'countryCode': 'AT'},
  {'city': 'Zurich', 'countryCode': 'CH'},
  {'city': 'Geneva', 'countryCode': 'CH'},
  {'city': 'Bern', 'countryCode': 'CH'},
  {'city': 'Stockholm', 'countryCode': 'SE'},
  {'city': 'Gothenburg', 'countryCode': 'SE'},
  {'city': 'Copenhagen', 'countryCode': 'DK'},
  {'city': 'Helsinki', 'countryCode': 'FI'},
  {'city': 'Oslo', 'countryCode': 'NO'},
  {'city': 'Reykjavik', 'countryCode': 'IS'},
  {'city': 'Dublin', 'countryCode': 'IE'},
  {'city': 'Belfast', 'countryCode': 'GB'},
  {'city': 'Edinburgh', 'countryCode': 'GB'},
  {'city': 'Glasgow', 'countryCode': 'GB'},
  {'city': 'Cardiff', 'countryCode': 'GB'},
  {'city': 'Wellington', 'countryCode': 'NZ'},
  {'city': 'Auckland', 'countryCode': 'NZ'},
  {'city': 'Christchurch', 'countryCode': 'NZ'},
  {'city': 'Brisbane', 'countryCode': 'AU'},
  {'city': 'Melbourne', 'countryCode': 'AU'},
  {'city': 'Sydney', 'countryCode': 'AU'},
  {'city': 'Perth', 'countryCode': 'AU'},
  {'city': 'Adelaide', 'countryCode': 'AU'},
  {'city': 'Lima', 'countryCode': 'PE'},
  {'city': 'Buenos Aires', 'countryCode': 'AR'},
  {'city': 'Santiago', 'countryCode': 'CL'},
  {'city': 'Rio de Janeiro', 'countryCode': 'BR'},
  {'city': 'São Paulo', 'countryCode': 'BR'},
  {'city': 'Bogotá', 'countryCode': 'CO'},
  {'city': 'Caracas', 'countryCode': 'VE'},
  {'city': 'Quito', 'countryCode': 'EC'},
  {'city': 'Asunción', 'countryCode': 'PY'},
  {'city': 'Montevideo', 'countryCode': 'UY'},
  {'city': 'La Paz', 'countryCode': 'BO'},
  {'city': 'Kiev', 'countryCode': 'UA'},
  {'city': 'Minsk', 'countryCode': 'BY'},
  {'city': 'Warsaw', 'countryCode': 'PL'},
  {'city': 'Budapest', 'countryCode': 'HU'},
  {'city': 'Prague', 'countryCode': 'CZ'},
  {'city': 'Bratislava', 'countryCode': 'SK'},
  {'city': 'Ljubljana', 'countryCode': 'SI'},
  {'city': 'Riga', 'countryCode': 'LV'},
  {'city': 'Vilnius', 'countryCode': 'LT'},
  {'city': 'Tallinn', 'countryCode': 'EE'},
  {'city': 'Sarajevo', 'countryCode': 'BA'},
  {'city': 'Belgrade', 'countryCode': 'RS'},
  {'city': 'Zagreb', 'countryCode': 'HR'},
  {'city': 'Sofia', 'countryCode': 'BG'},
  {'city': 'Bucharest', 'countryCode': 'RO'},
  {'city': 'Chisinau', 'countryCode': 'MD'},
  {'city': 'Tbilisi', 'countryCode': 'GE'},
  {'city': 'Yerevan', 'countryCode': 'AM'},
  {'city': 'Baku', 'countryCode': 'AZ'},
  {'city': 'Astana', 'countryCode': 'KZ'},
  {'city': 'Almaty', 'countryCode': 'KZ'},
  {'city': 'Ulaanbaatar', 'countryCode': 'MN'},
  {'city': 'Dhaka', 'countryCode': 'BD'},
  {'city': 'Colombo', 'countryCode': 'LK'},
  {'city': 'Kathmandu', 'countryCode': 'NP'},
  {'city': 'Thimphu', 'countryCode': 'BT'},
  {'city': 'Male', 'countryCode': 'MV'},
  {'city': 'Vientiane', 'countryCode': 'LA'},
  {'city': 'Hanoi', 'countryCode': 'VN'},
  {'city': 'Ho Chi Minh City', 'countryCode': 'VN'},
  {'city': 'Yangon', 'countryCode': 'MM'},
  {'city': 'Phnom Penh', 'countryCode': 'KH'},
  {'city': 'Kuala Lumpur', 'countryCode': 'MY'},
  {'city': 'Singapore', 'countryCode': 'SG'},
  {'city': 'Manila', 'countryCode': 'PH'},
  {'city': 'Hong Kong', 'countryCode': 'HK'},
  {'city': 'Taipei', 'countryCode': 'TW'},
  {'city': 'Seoul', 'countryCode': 'KR'},
  {'city': 'Busan', 'countryCode': 'KR'},
  {'city': 'Dubai', 'countryCode': 'AE'},
  {'city': 'Abu Dhabi', 'countryCode': 'AE'},
  {'city': 'Doha', 'countryCode': 'QA'},
  {'city': 'Kuwait City', 'countryCode': 'KW'},
  {'city': 'Manama', 'countryCode': 'BH'},
  {'city': 'Riyadh', 'countryCode': 'SA'},
  {'city': 'Jeddah', 'countryCode': 'SA'},
  {'city': 'Cairo', 'countryCode': 'EG'},
  {'city': 'Alexandria', 'countryCode': 'EG'},
  {'city': 'Casablanca', 'countryCode': 'MA'},
  {'city': 'Rabat', 'countryCode': 'MA'},
  {'city': 'Tunis', 'countryCode': 'TN'},
  {'city': 'Algiers', 'countryCode': 'DZ'},
  {'city': 'Istanbul', 'countryCode': 'TR'},
  {'city': 'Ankara', 'countryCode': 'TR'},
  {'city': 'Athens', 'countryCode': 'GR'},
  {'city': 'Thessaloniki', 'countryCode': 'GR'},
  {'city': 'Vienna', 'countryCode': 'AT'},
  {'city': 'Graz', 'countryCode': 'AT'},
  {'city': 'Zurich', 'countryCode': 'CH'},
  {'city': 'Geneva', 'countryCode': 'CH'},
  {'city': 'Bern', 'countryCode': 'CH'},
  {'city': 'Stockholm', 'countryCode': 'SE'},
  {'city': 'Gothenburg', 'countryCode': 'SE'},
  {'city': 'Copenhagen', 'countryCode': 'DK'},
  {'city': 'Helsinki', 'countryCode': 'FI'},
  {'city': 'Oslo', 'countryCode': 'NO'},
  {'city': 'Reykjavik', 'countryCode': 'IS'},
  {'city': 'Dublin', 'countryCode': 'IE'},
  {'city': 'Belfast', 'countryCode': 'GB'},
  {'city': 'Edinburgh', 'countryCode': 'GB'},
  {'city': 'Glasgow', 'countryCode': 'GB'},
  {'city': 'Cardiff', 'countryCode': 'GB'},
  {'city': 'Wellington', 'countryCode': 'NZ'},
  {'city': 'Auckland', 'countryCode': 'NZ'},
  {'city': 'Christchurch', 'countryCode': 'NZ'},
  {'city': 'Brisbane', 'countryCode': 'AU'},
  {'city': 'Melbourne', 'countryCode': 'AU'},
  {'city': 'Sydney', 'countryCode': 'AU'},
  {'city': 'Perth', 'countryCode': 'AU'},
  {'city': 'Adelaide', 'countryCode': 'AU'},
  {'city': 'Lima', 'countryCode': 'PE'},
  {'city': 'Buenos Aires', 'countryCode': 'AR'},
  {'city': 'Santiago', 'countryCode': 'CL'},
  {'city': 'Rio de Janeiro', 'countryCode': 'BR'},
  {'city': 'São Paulo', 'countryCode': 'BR'},
  {'city': 'Bogotá', 'countryCode': 'CO'},
  {'city': 'Caracas', 'countryCode': 'VE'},
  {'city': 'Quito', 'countryCode': 'EC'},
  {'city': 'Asunción', 'countryCode': 'PY'},
  {'city': 'Montevideo', 'countryCode': 'UY'},
  {'city': 'La Paz', 'countryCode': 'BO'},
  {'city': 'Kiev', 'countryCode': 'UA'},
  {'city': 'Minsk', 'countryCode': 'BY'},
  {'city': 'Warsaw', 'countryCode': 'PL'},
  {'city': 'Budapest', 'countryCode': 'HU'},
  {'city': 'Prague', 'countryCode': 'CZ'},
  {'city': 'Bratislava', 'countryCode': 'SK'},
  {'city': 'Ljubljana', 'countryCode': 'SI'},
  {'city': 'Riga', 'countryCode': 'LV'},
  {'city': 'Vilnius', 'countryCode': 'LT'},
  {'city': 'Tallinn', 'countryCode': 'EE'},
  {'city': 'Sarajevo', 'countryCode': 'BA'},
  {'city': 'Belgrade', 'countryCode': 'RS'},
  {'city': 'Zagreb', 'countryCode': 'HR'},
  {'city': 'Sofia', 'countryCode': 'BG'},
  {'city': 'Bucharest', 'countryCode': 'RO'},
  {'city': 'Chisinau', 'countryCode': 'MD'},
  {'city': 'Tbilisi', 'countryCode': 'GE'},
  {'city': 'Yerevan', 'countryCode': 'AM'},
  {'city': 'Baku', 'countryCode': 'AZ'},
  {'city': 'Astana', 'countryCode': 'KZ'},
  {'city': 'Almaty', 'countryCode': 'KZ'},
  {'city': 'Ulaanbaatar', 'countryCode': 'MN'},
  {'city': 'Dhaka', 'countryCode': 'BD'},
  {'city': 'Colombo', 'countryCode': 'LK'},
  {'city': 'Kathmandu', 'countryCode': 'NP'},
  {'city': 'Thimphu', 'countryCode': 'BT'},
  {'city': 'Male', 'countryCode': 'MV'},
  {'city': 'Vientiane', 'countryCode': 'LA'},
  {'city': 'Hanoi', 'countryCode': 'VN'},
  {'city': 'Ho Chi Minh City', 'countryCode': 'VN'},
  {'city': 'Yangon', 'countryCode': 'MM'},
  {'city': 'Phnom Penh', 'countryCode': 'KH'},
  {'city': 'Kuala Lumpur', 'countryCode': 'MY'},
  {'city': 'Singapore', 'countryCode': 'SG'},
  {'city': 'Manila', 'countryCode': 'PH'},
  {'city': 'Hong Kong', 'countryCode': 'HK'},
  {'city': 'Taipei', 'countryCode': 'TW'},
  {'city': 'Seoul', 'countryCode': 'KR'},
  {'city': 'Busan', 'countryCode': 'KR'},
  {'city': 'Dubai', 'countryCode': 'AE'},
  {'city': 'Abu Dhabi', 'countryCode': 'AE'},
  {'city': 'Doha', 'countryCode': 'QA'},
  {'city': 'Kuwait City', 'countryCode': 'KW'},
  {'city': 'Manama', 'countryCode': 'BH'},
  {'city': 'Riyadh', 'countryCode': 'SA'},
  {'city': 'Jeddah', 'countryCode': 'SA'},
  {'city': 'Cairo', 'countryCode': 'EG'},
  {'city': 'Alexandria', 'countryCode': 'EG'},
  {'city': 'Casablanca', 'countryCode': 'MA'},
  {'city': 'Rabat', 'countryCode': 'MA'},
  {'city': 'Tunis', 'countryCode': 'TN'},
  {'city': 'Algiers', 'countryCode': 'DZ'},
  {'city': 'Istanbul', 'countryCode': 'TR'},
  {'city': 'Ankara', 'countryCode': 'TR'},
  {'city': 'Athens', 'countryCode': 'GR'},
  {'city': 'Thessaloniki', 'countryCode': 'GR'},
  {'city': 'Vienna', 'countryCode': 'AT'},
  {'city': 'Graz', 'countryCode': 'AT'},
  {'city': 'Zurich', 'countryCode': 'CH'},
  {'city': 'Geneva', 'countryCode': 'CH'},
  {'city': 'Bern', 'countryCode': 'CH'},
  {'city': 'Stockholm', 'countryCode': 'SE'},
  {'city': 'Gothenburg', 'countryCode': 'SE'},
  {'city': 'Copenhagen', 'countryCode': 'DK'},
  {'city': 'Helsinki', 'countryCode': 'FI'},
  {'city': 'Oslo', 'countryCode': 'NO'},
  {'city': 'Reykjavik', 'countryCode': 'IS'},
  {'city': 'Dublin', 'countryCode': 'IE'},
  {'city': 'Belfast', 'countryCode': 'GB'},
  {'city': 'Edinburgh', 'countryCode': 'GB'},
  {'city': 'Glasgow', 'countryCode': 'GB'},
  {'city': 'Cardiff', 'countryCode': 'GB'},
  {'city': 'Wellington', 'countryCode': 'NZ'},
  {'city': 'Auckland', 'countryCode': 'NZ'},
  {'city': 'Christchurch', 'countryCode': 'NZ'},
  {'city': 'Brisbane', 'countryCode': 'AU'},
  {'city': 'Melbourne', 'countryCode': 'AU'},
  {'city': 'Sydney', 'countryCode': 'AU'},
  {'city': 'Perth', 'countryCode': 'AU'},
  {'city': 'Adelaide', 'countryCode': 'AU'},
];
